version: 2
cli:
  server: https://app.fossa.com
  fetcher: custom
  project: git@github.com:kelda-inc/kelda
analyze:
  modules:
    - name: github.com/sidkik/kelda-v1
      type: go
      target: github.com/sidkik/kelda-v1
      path: .
    - name: github.com/sidkik/kelda-v1/scripts/download-analytics
      type: go
      target: github.com/sidkik/kelda-v1/scripts/download-analytics
      path: scripts/download-analytics
    - name: github.com/sidkik/kelda-v1/scripts/make-license
      type: go
      target: github.com/sidkik/kelda-v1/scripts/make-license
      path: scripts/make-license
