package logs

import (
	"bufio"
	"context"
	"fmt"
	"hash/fnv"
	"io"
	"os"
	"os/signal"
	"sort"
	"strings"
	"sync"
	"syscall"
	"time"

	"github.com/buger/goterm"
	"github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
	core "k8s.io/api/core/v1"
	"k8s.io/client-go/kubernetes"

	"github.com/kelda-inc/kelda/cmd/util"
	"github.com/kelda-inc/kelda/pkg/config"
	keldaClientset "github.com/kelda-inc/kelda/pkg/crd/client/clientset/versioned"
	"github.com/kelda-inc/kelda/pkg/errors"
)

var stdout io.Writer = os.Stdout

type logsCommand struct {
	keldaClient keldaClientset.Interface
	kubeClient  kubernetes.Interface
	services    []string
	opts        core.PodLogOptions
	namespace   string
}

type rawLogLine struct {
	// Any error that occurred when trying to read logs.
	// If this is non-nil, `message` and `receivedAt` aren't meaningful.
	readError error

	// The Kelda service that generated the log.
	fromService string

	// The contents of the log line (including the timestamp added by Kubernetes).
	message string

	// The time that we read the log line.
	receivedAt time.Time
}

type parsedLogLine struct {
	// The Kelda service that generated the log.
	fromService string

	// The contents of the log line (without the timestamp added by Kubernetes).
	message string

	// The time that the log line was generated by the application according to
	// the machine that the container is running on.
	loggedAt time.Time
}

// New creates a new `logs` command.
func New() *cobra.Command {
	cmd := logsCommand{}

	cobraCmd := &cobra.Command{
		Use:   "logs service ...",
		Short: "Print the logs for the given services",
		Long: "Print the logs for the given services.\n\n" +
			"`kelda logs` assumes that each service has exactly one pod.\n" +
			"If the pod has more than one container, the first container in " +
			"the Kubernetes manifest is used.",
		Run: func(_ *cobra.Command, args []string) {
			switch len(args) {
			case 0:
				util.HandleFatalError(util.ErrMissingServiceName)
			default:
				cmd.services = args
			}

			userConfig, err := config.ParseUser()
			if err != nil {
				util.HandleFatalError(errors.WithContext(err, "parse user config"))
			}

			kubeClient, restConfig, err := util.GetKubeClient(userConfig.Context)
			if err != nil {
				util.HandleFatalError(errors.WithContext(err, "get kube client"))
			}

			keldaClient, err := keldaClientset.NewForConfig(restConfig)
			if err != nil {
				util.HandleFatalError(errors.WithContext(err, "get kelda client"))
			}

			cmd.keldaClient = keldaClient
			cmd.kubeClient = kubeClient
			cmd.namespace = userConfig.Namespace
			if err := cmd.run(); err != nil {
				util.HandleFatalError(err)
			}
		},
	}

	cobraCmd.Flags().BoolVarP(&cmd.opts.Follow, "follow", "f", false,
		"Specify if the logs should be streamed.")
	cobraCmd.Flags().BoolVarP(&cmd.opts.Previous, "previous", "p", false,
		"If true, print the logs for the previous instance of the container in a pod if it exists.")

	return cobraCmd
}

func (cmd logsCommand) run() error {
	// Exit gracefully when the user Ctrl-C's.
	// The `printLogs` function will return when the context is cancelled,
	// which allows functions defered in this method to run.
	signalChan := make(chan os.Signal, 1)
	signal.Notify(signalChan, os.Interrupt, syscall.SIGTERM)
	ctx, cancel := context.WithCancel(context.Background())
	go func() {
		<-signalChan
		cancel()
	}()

	var wg sync.WaitGroup
	combinedLogs := make(chan rawLogLine, len(cmd.services)*32)
	for _, service := range cmd.services {
		podName, containerName, err := util.ResolvePodName(cmd.keldaClient, cmd.namespace, service)
		if err != nil {
			return errors.WithContext(err, "resolve service to pod")
		}

		// Enable timestamps so that `forwardLogs` can parse the logs.
		cmd.opts.Timestamps = true
		cmd.opts.Container = containerName
		logsReq := cmd.kubeClient.CoreV1().
			Pods(cmd.namespace).
			GetLogs(podName, &cmd.opts)

		logsStream, err := logsReq.Stream()
		if err != nil {
			return errors.WithContext(err, "start logs stream")
		}
		defer logsStream.Close()

		wg.Add(1)
		go func(service string) {
			forwardLogs(combinedLogs, service, logsStream)
			wg.Done()
		}(service)
	}

	// No more log messages will be written to the channel once all the
	// `forwardLogs` threads finish.
	go func() {
		wg.Wait()
		close(combinedLogs)
	}()

	noColor := len(cmd.services) == 1
	return printLogs(ctx, combinedLogs, noColor)
}

// forwardLogs forwards each log line from `logsReq` to the `combinedLogs`
// channel.
func forwardLogs(combinedLogs chan<- rawLogLine, service string, logsStream io.ReadCloser) {
	scanner := bufio.NewScanner(logsStream)
	for {
		scanned := scanner.Scan()
		if !scanned {
			// The error will be `nil` if we didn't scan because the stream has
			// ended.
			if err := scanner.Err(); err != nil {
				combinedLogs <- rawLogLine{fromService: service, readError: err}
			}
			return
		}

		combinedLogs <- rawLogLine{
			fromService: service,
			message:     scanner.Text(),
			receivedAt:  time.Now(),
		}
	}
}

// The logs within a window are guaranteed to be sorted.
// Note that it's still possible for a delayed log to arrive in the next
// window, in which case it will be printed out of order.
const windowSize = 100 * time.Millisecond

// printLogs reads logs from the `rawLogs` in `windowSize` intervals, and
// prints the logs in each window in sorted order.
func printLogs(ctx context.Context, rawLogs <-chan rawLogLine, noColor bool) error {
	var window []rawLogLine
	var flushTrigger <-chan time.Time

	// flush prints the logs in the current window to the terminal.
	flush := func() {
		// Parse the logs in the windows to extract their timestamps.
		var parsedLogs []parsedLogLine
		for _, rawLog := range window {
			message, timestamp, err := parseLogLine(rawLog.message)

			// If we fail to parse the log's timestamp, revert to sorting based
			// on its receival time.
			if err != nil {
				logrus.WithField("message", rawLog.message).
					WithField("service", rawLog.fromService).
					WithError(err).Warn("Failed to parse timestamp")
				message = rawLog.message
				timestamp = rawLog.receivedAt
			}

			parsedLogs = append(parsedLogs, parsedLogLine{
				fromService: rawLog.fromService,
				message:     message,
				loggedAt:    timestamp,
			})
		}

		// Sort logs in the window.
		byLogTime := func(i, j int) bool {
			return parsedLogs[i].loggedAt.Before(parsedLogs[j].loggedAt)
		}
		sort.Slice(parsedLogs, byLogTime)

		// Print the logs.
		for _, log := range parsedLogs {
			if noColor {
				fmt.Fprintln(stdout, log.message)
			} else {
				coloredService := goterm.Color(log.fromService, pickColor(log.fromService))
				fmt.Fprintf(stdout, "%s › %s\n", coloredService, log.message)
			}
		}

		// Clear the buffer now that we've printed its contents.
		window = nil
	}

	for {
		select {
		case logLine, ok := <-rawLogs:
			if !ok {
				// There won't be any more messages, so we can exit after
				// flushing any unprinted logs.
				flush()
				return nil
			}

			if logLine.readError != nil {
				errCtx := fmt.Sprintf("read logs for %s", logLine.fromService)
				return errors.WithContext(logLine.readError, errCtx)
			}

			// Wake up later to flush the buffered lines.
			window = append(window, logLine)
			if flushTrigger == nil {
				flushTrigger = time.After(windowSize)
			}
		case <-flushTrigger:
			flush()
			flushTrigger = nil
		case <-ctx.Done():
			return nil
		}
	}
}

func parseLogLine(rawMessage string) (string, time.Time, error) {
	logParts := strings.SplitN(rawMessage, " ", 2)
	if len(logParts) != 2 {
		return "", time.Time{}, errors.New("malformed line")
	}

	rawTimestamp := logParts[0]
	timestamp, err := time.Parse(time.RFC3339Nano, rawTimestamp)
	if err != nil {
		// According to the Kubernetes docs, the timestamp might be in the
		// RFC3339 or RFC3339Nano format.
		timestamp, err = time.Parse(time.RFC3339, rawTimestamp)
		if err != nil {
			return "", time.Time{},
				errors.New("parse timestamp")
		}
	}

	message := logParts[1]
	return message, timestamp, nil
}

var colorList = []int{
	goterm.BLUE,
	goterm.CYAN,
	goterm.GREEN,
	goterm.MAGENTA,
	goterm.RED,
	goterm.YELLOW,
}

func pickColor(service string) int {
	hash := fnv.New32()
	hash.Write([]byte(service))
	idx := hash.Sum32() % uint32(len(colorList))
	return colorList[idx]
}
