// Code generated by mockery v1.0.0. DO NOT EDIT.

package tunnel

import mock "github.com/stretchr/testify/mock"

// mockTunnelManager is an autogenerated mock type for the tunnelManager type
type mockTunnelManager struct {
	mock.Mock
}

// Start provides a mock function with given fields:
func (_m *mockTunnelManager) Start() {
	_m.Called()
}

// Stop provides a mock function with given fields:
func (_m *mockTunnelManager) Stop() {
	_m.Called()
}
