#!/bin/bash
set -e

website_path="$GOPATH/src/github.com/kelda-inc/kelda.io"
docs_out_path="${website_path}/site/static/docs"
version_path="${website_path}/docs_version"

function assert_repo() {
    repo_path=$1
    exp_branch=$2
    cd ${repo_path}

    if [[ -n "${exp_branch}" && $(git rev-parse --abbrev-ref HEAD) != "${exp_branch}" ]]; then
        echo "Aborting. Repo not checked out to ${exp_branch}."
        exit 1
    fi

    if [[ -n $(git status -s) ]]; then
        echo "Aborting. Repo contains uncommitted files."
        exit 1
    fi

    cd - >/dev/null
}

assert_repo . master
assert_repo "${website_path}"

updates="$(git log $(cat "${version_path}")..HEAD -- docs)"

make build-docs
rm -rf "${docs_out_path}"
cp -r docs/site "${docs_out_path}"

git rev-parse HEAD > "${version_path}"

cd "${website_path}"
git add .
git commit -m "docs: Sync updates from kelda-inc/kelda" \
    -m "This commit was autogenerated by scripts/upload_docs.sh in the kelda-inc/kelda repo." \
    -m "${updates}"

echo "Successfully updated docs at ${website_path}"
echo "Push the new commit to deploy via Netlify"
